services:
  crud:
    image: mysql:latest
    container_name: crud
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"